# """
# Django settings for automaticExtractionBackend project.
#
# Generated by 'django-admin startproject' using Django 4.0.1.
#
# For more information on this file, see
# https://docs.djangoproject.com/en/4.0/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/4.0/ref/settings/
# """
# import os
# from pathlib import Path
#
# import dj_database_url
# from dotenv import load_dotenv
#
# load_dotenv()
# env = os.environ.copy()
# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
#
#
# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/
#
# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-vfci_hhk5t#f$nda-lr6oafq$3u)!h5a8yqa!23#&gawqq8fh1'
#
# IS_HEROKU_APP = "DYNO" in os.environ and "CI" not in os.environ
# # SECURITY WARNING: don't run with debug turned on in production!
# # DEBUG = True
#
# if IS_HEROKU_APP:
#     DEBUG = False
# else:
#     DEBUG = True
#
#
# # ALLOWED_HOSTS = []
# ALLOWED_HOSTS = ["*"]
# # ALLOWED_HOSTS = [".localhost", "127.0.0.1", "[::1]", "0.0.0.0", "[::]"]
#
#
# # Application definition
#
# INSTALLED_APPS = [
#     "daphne",   # asgi 应用，如果不设置，默认为 wsgi 应用
#     "whitenoise.runserver_nostatic",  # deploy addition
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'rest_framework',
#     'corsheaders',  # 确保已安装
#     "channels",  # add for threads
#     'automaticExtractionBackend',
# ]
#
# MIDDLEWARE = [
#     'corsheaders.middleware.CorsMiddleware',  # cors problem
#     'django.middleware.security.SecurityMiddleware',
#     "whitenoise.middleware.WhiteNoiseMiddleware",  # deploy addition
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     # 'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]
#
# ROOT_URLCONF = 'automaticExtractionBackend.urls'
#
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [Path(BASE_DIR, 'templates')], # 项目的全局模板
#         'APP_DIRS': True,   # 自动加载所有应用中的 templates 模板
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]
#
# WSGI_APPLICATION = 'automaticExtractionBackend.wsgi.application'
# ASGI_APPLICATION = 'automaticExtractionBackend.asgi.application'
#
# # 静态文件路径（Vue 构建后会复制到这里）
# STATIC_URL = "/static/"
# STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]  # 让 Django 识别 static 目录
# STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  # 用于 collectstatic
#
#
# # Database
# # https://docs.djangoproject.com/en/4.0/ref/settings/#databases
#
# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.sqlite3',
# #         'NAME': BASE_DIR / 'db.sqlite3',
# #     }
# # }
#
#
# if DEBUG:
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.sqlite3',
#             'NAME': BASE_DIR / 'db.sqlite3',
#         }
#     }
#
# else:
#     # 生产环境使用 PostgreSQL 数据库
#     # 记得在配置环境变量的时候把这些东西都配好
#     # DATABASE_URL = "postgres://track_user:track_password@track_postgres:5432/track_db"
#     # DATABASES = {
#     #     "default": {
#     #         "ENGINE": "django.db.backends.postgresql",
#     #         "NAME": os.getenv("POSTGRES_DB", "track_db"),
#     #         "USER": os.getenv("POSTGRES_USER", "track_user"),
#     #         "PASSWORD": os.getenv("POSTGRES_PASSWORD", "track_password"),
#     #         "HOST": os.getenv("POSTGRES_HOST", "track_postgres"),  # Docker 容器内的数据库地址
#     #         "PORT": os.getenv("POSTGRES_PORT", "5432"),
#     #     }
#     # }
#
#     DATABASES = {
#         "default": dj_database_url.config(
#             env="DATABASE_URL",
#             conn_max_age=600,
#             conn_health_checks=True,
#             ssl_require=True,
#         ),
#     }
#
# # Password validation
# # https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators
#
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]
#
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
#
# if DEBUG:
#     CHANNEL_LAYERS = {
#         "default": {
#             "BACKEND": "channels.layers.InMemoryChannelLayer",
#         }
#     }
# else:
#     CHANNEL_LAYERS = {
#         "default": {
#             "BACKEND": "channels_redis.core.RedisChannelLayer",
#             "CONFIG": {
#                 "hosts": [("redis", 6379)],
#             },
#         }
#     }
#
# # Internationalization
# # https://docs.djangoproject.com/en/4.0/topics/i18n/
#
# LANGUAGE_CODE = 'en-us'
#
# TIME_ZONE = 'UTC'
#
# USE_I18N = True
#
# USE_TZ = True
#
#
#
# # Default primary key field type
# # https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field
#
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#
# OPENAI_API_KEY = env.get("OPENAI_API_KEY")
#
#
# CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOW_CREDENTIALS = True
#
#
# EMBEDDING_MODEL = 'text-embedding-3-large'  # 3072
# # EMBEDDING_MODEL = 'text-embedding-3-small'  # 1536
#
# EMBEDDING_MODELS = [EMBEDDING_MODEL]
















"""
 @file: settings_aws_template.py
 @Time    : 2025/6/13
 @Author  : Peinuan qin
 """
import json
from urllib.parse import urlparse

from langchain_openai import ChatOpenAI
from openai import AsyncOpenAI

"""
Django settings for automaticExtractionBackend project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv, find_dotenv

# load_dotenv()
# env = os.environ.copy()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# 查找 .env 文件并加载
dotenv_path = find_dotenv(str(BASE_DIR / ".env"))
if load_dotenv(dotenv_path):
    print(f"✅ Successfully loaded .env from {dotenv_path}")
else:
    print("⚠️ No .env file found or failed to load.")

# load_dotenv(dotenv_path=BASE_DIR / ".env")
env = os.environ.copy()



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vfci_hhk5t#f$nda-lr6oafq$3u)!h5a8yqa!23#&gawqq8fh1'

DEBUG = os.getenv("DEBUG", "False").lower() == "true"
# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True


# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ["*"]
# ALLOWED_HOSTS = [".localhost", "127.0.0.1", "[::1]", "0.0.0.0", "[::]"]


# Application definition

INSTALLED_APPS = [
    "daphne",   # asgi 应用，如果不设置，默认为 wsgi 应用
    "whitenoise.runserver_nostatic",  # deploy addition
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',  # 确保已安装
    "channels",  # add for threads
    'automaticExtractionBackend',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # cors problem
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",  # deploy addition
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'automaticExtractionBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [Path(BASE_DIR, 'templates')], # 项目的全局模板
        'APP_DIRS': True,   # 自动加载所有应用中的 templates 模板
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'automaticExtractionBackend.wsgi.application'
ASGI_APPLICATION = 'automaticExtractionBackend.asgi.application'

# 静态文件路径（Vue 构建后会复制到这里）
STATIC_URL = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]  # 让 Django 识别 static 目录
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  # 用于 collectstatic


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


if DEBUG:
    # DATABASES = {
    #     'default': {
    #         'ENGINE': 'django.db.backends.sqlite3',
    #         'NAME': BASE_DIR / 'db.sqlite3',
    #         'CONN_MAX_AGE': 300,  # 连接池保持时间（秒）
    #     }
    # }
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv("POSTGRES_DB", "your_local_db_name"),
            'USER': os.getenv("POSTGRES_USER", "your_local_db_user"),
            'PASSWORD': os.getenv("POSTGRES_PASSWORD", "your_local_db_password"),
            'HOST': os.getenv("POSTGRES_HOST", "localhost"),
            'PORT': os.getenv("POSTGRES_PORT", "5432"),
            'CONN_MAX_AGE': 300,
        }
    }

else:
    DATABASES = {
        "default": dj_database_url.config(
            default=os.getenv("DATABASE_URL"),
            conn_max_age=300,
            conn_health_checks=True,
        )
    }

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

if DEBUG:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [("redis", 6379)],
            },
        }
    }

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

OPENAI_API_KEY = env.get("OPENAI_API_KEY")


OPENAI_KEYS = os.getenv("OPENAI_KEYS", "[]")
OPENAI_KEYS = json.loads(OPENAI_KEYS)




CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True


EMBEDDING_MODEL = 'text-embedding-3-large'  # 3072
# EMBEDDING_MODEL = 'text-embedding-3-small'  # 1536

EMBEDDING_MODELS = [EMBEDDING_MODEL]


# Service Connection Check Logs (only for initial debugging, safe to remove later)
import psycopg2
import redis

if not DEBUG:
    print("🧪 [PRODUCTION MODE] Checking container-based PostgreSQL and Redis connections...")

    # Parse DATABASE_URL
    db_url = os.getenv("DATABASE_URL")
    if db_url:
        try:
            parsed = urlparse(db_url)
            conn = psycopg2.connect(
                dbname=parsed.path.lstrip("/"),
                user=parsed.username,
                password=parsed.password,
                host=parsed.hostname,
                port=parsed.port,
            )
            print("✅ Successfully connected to PostgreSQL via DATABASE_URL!")
            conn.close()
        except Exception as e:
            print(f"❌ PostgreSQL Connection Error via DATABASE_URL: {e}")
    else:
        print("❌ DATABASE_URL is not set!")

    # Redis 连接检查
    try:
        redis_host = os.getenv("REDIS_HOST", "redis")
        redis_port = int(os.getenv("REDIS_PORT", 6379))
        redis_client = redis.Redis(
            host=redis_host,
            port=redis_port,
            db=0,
            decode_responses=True,
        )
        redis_client.ping()
        print(f"✅ Successfully connected to Redis at {redis_host}:{redis_port}!")
    except Exception as e:
        print(f"❌ Redis Connection Error (production): {e}")

else:
    print("🧪 [LOCAL DEBUG MODE] Checking PostgreSQL connection from .env...")

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv("POSTGRES_DB"),
            'USER': os.getenv("POSTGRES_USER"),
            'PASSWORD': os.getenv("POSTGRES_PASSWORD"),
            'HOST': os.getenv("POSTGRES_HOST", "localhost"),
            'PORT': os.getenv("POSTGRES_PORT", "5432"),
            'CONN_MAX_AGE': 300,
        }
    }

    # 检查本地 PostgreSQL 连接（可选）
    try:
        import psycopg2

        conn = psycopg2.connect(
            dbname=os.getenv("POSTGRES_DB", "local_db"),
            user=os.getenv("POSTGRES_USER", "local_user"),
            password=os.getenv("POSTGRES_PASSWORD", "local_password"),
            host=os.getenv("POSTGRES_HOST", "localhost"),
            port=os.getenv("POSTGRES_PORT", "5432"),
        )
        print("✅ Successfully connected to LOCAL PostgreSQL!")
        conn.close()
    except Exception as e:
        print(f"❌ LOCAL PostgreSQL connection failed: {e}")

# 使用 Whitenoise 的存储后端，但跳过对 admin 和 rest_framework 文件的哈希处理
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}



# 跳过哈希处理的文件（匹配路径）
WHITENOISE_IMMUTABLE_FILE_TEST = lambda path, url: (
    url.startswith("admin/") or
    url.startswith("rest_framework/")
)

# 启用 Whitenoise 压缩和缓存
WHITENOISE_KEEP_ONLY_HASHED_FILES = True  # 仅保留哈希后的文件
WHITENOISE_USE_FINDERS = True             # 允许 Whitenoise 查找静态文件
WHITENOISE_MANIFEST_STRICT = False        # 避免因缺失文件报错


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



from random import choice
from threading import Lock

# 全局 LLM 池
LLM_POOL = []
LLM_POOL_LOCK = Lock()


# 随机挑选的方式
#
# def initialize_llm_pool():
#     global LLM_POOL
#     with LLM_POOL_LOCK:
#         if not LLM_POOL:
#             for key in OPENAI_KEYS:
#                 llm = ChatOpenAI(openai_api_key=key, model="gpt-4o", temperature=0)
#                 LLM_POOL.append(llm)


def initialize_llm_pool():
    global LLM_POOL
    with LLM_POOL_LOCK:
        if not LLM_POOL:
            for key in OPENAI_KEYS:
                llm = ChatOpenAI(
                    openai_api_key=key,
                    model="gpt-4o",
                    temperature=0,
                )
                LLM_POOL.append(llm)


def get_llm_instance():
    if not LLM_POOL:
        initialize_llm_pool()
    return choice(LLM_POOL)


#
# from itertools import cycle
#
# _llm_cycle = None
#
# def initialize_llm_cycle():
#     global _llm_cycle
#     if not _llm_cycle:
#         initialize_llm_pool()
#         _llm_cycle = cycle(LLM_POOL)
#
# def get_llm_instance():
#     initialize_llm_cycle()
#     return next(_llm_cycle)
