# Generated by Django 4.0.1 on 2025-04-06 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Construct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('definition', models.TextField()),
                ('examples', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('embeddings', models.JSONField(blank=True, default=dict)),
                ('construct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automaticExtractionBackend.construct')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Triple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cause_triples', to='automaticExtractionBackend.entity')),
                ('entity_effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect_triples', to='automaticExtractionBackend.entity')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triples', to='automaticExtractionBackend.sentence')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triples', to='automaticExtractionBackend.systemuser')),
            ],
        ),
        migrations.AddField(
            model_name='sentence',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='automaticExtractionBackend.systemuser'),
        ),
        migrations.AddField(
            model_name='entity',
            name='sentence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='automaticExtractionBackend.sentence'),
        ),
        migrations.AddField(
            model_name='entity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='automaticExtractionBackend.systemuser'),
        ),
        migrations.AddField(
            model_name='construct',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constructs', to='automaticExtractionBackend.systemuser'),
        ),
    ]
