# Generated by Django 4.0.1 on 2025-04-09 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automaticExtractionBackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='canonical_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automaticExtractionBackend.entity'),
        ),
    ]
