# Generated by Django 4.0.1 on 2025-05-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaticExtractionBackend', '0002_entity_canonical_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='color',
            field=models.CharField(default='#cccccc', max_length=20),
        ),
        migrations.AddField(
            model_name='sentence',
            name='line_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
