# Generated by Django 4.0.1 on 2025-06-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaticExtractionBackend', '0003_entity_color_sentence_line_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='construct',
            name='color',
            field=models.CharField(default='#cccccc', max_length=20),
        ),
    ]
