# Generated by Django 4.0.1 on 2025-07-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automaticExtractionBackend', '0004_construct_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='construct',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='sentence',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='systemuser',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='triple',
            options={'base_manager_name': 'objects'},
        ),
    ]
