# Generated by Django 4.0.1 on 2025-07-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automaticExtractionBackend', '0005_alter_construct_options_alter_entity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='construct',
            options={},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sentence',
            options={},
        ),
        migrations.AlterModelOptions(
            name='systemuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='triple',
            options={},
        ),
    ]
