# Generated by Django 4.0.1 on 2025-07-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaticExtractionBackend', '0006_alter_construct_options_alter_entity_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='triple',
            constraint=models.UniqueConstraint(fields=('user', 'sentence', 'entity_cause', 'entity_effect'), name='unique_triple'),
        ),
    ]
