# Generated by Django 4.0.1 on 2025-05-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_entity_color_sentence_line_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='color',
        ),
        migrations.AddField(
            model_name='construct',
            name='color',
            field=models.CharField(default='#cccccc', max_length=20),
        ),
    ]
